//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventHead
    {
        public System.Web.HttpPostedFileBase Imagefile { get; set; }
        public string ProfilePhoto { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string RegNo { get; set; }
        public string Pwd { get; set; }
    }
}
