//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventRegistration
    {
        public int EventId { get; set; }
        public string Participant1Email { get; set; }
        public string Participant2Email { get; set; }
        public Nullable<bool> OnlinePayment { get; set; }
        public Nullable<bool> PaymentConfirmed { get; set; }
    
        public virtual tblParticipant tblParticipant { get; set; }
        public virtual tblParticipant tblParticipant1 { get; set; }
    }
}
