//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public int EventID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartData { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Coverphoto { get; set; }
        public Nullable<bool> isEnd { get; set; }
        public int Price { get; set; }
        public Nullable<int> MaximumMembersAllowed { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tblOrganizer tblOrganizer { get; set; }
        public System.Web.HttpPostedFileBase Imagefile { get; set; }
    }
}
