//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbTechFestEntities : DbContext
    {
        public dbTechFestEntities()
            : base("name=dbTechFestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEvent> tblEvents { get; set; }
        public virtual DbSet<tblEventHead> tblEventHeads { get; set; }
        public virtual DbSet<tblEventRegistration> tblEventRegistrations { get; set; }
        public virtual DbSet<tblOrganizer> tblOrganizers { get; set; }
        public virtual DbSet<tblParticipant> tblParticipants { get; set; }
    }
}
